version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=8888
      - SOURCE_DB_HOST=${SOURCE_DB_HOST}
      - SOURCE_DB_PORT=${SOURCE_DB_PORT}
      - SOURCE_DB_USER=${SOURCE_DB_USER}
      - SOURCE_DB_PASSWORD=${SOURCE_DB_PASSWORD}
      - SOURCE_DB_NAME=${SOURCE_DB_NAME}
      - DESTINATION_DB_HOST=${DESTINATION_DB_HOST}
      - DESTINATION_DB_PORT=${DESTINATION_DB_PORT}
      - DESTINATION_DB_USER=${DESTINATION_DB_USER}
      - DESTINATION_DB_PASSWORD=${DESTINATION_DB_PASSWORD}
      - DESTINATION_DB_NAME=${DESTINATION_DB_NAME}
    networks:
      - app-network


networks:
  app-network: